[project]
name = "hexagonal-llm"
version = "0.1.0"
description = "Open Food Facts with AI"
authors = [{name = "danielemegna"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.0.0",
    "pyyaml>=6.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1,<10.0.0",
]

[project.scripts]
main = "main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["aifoodfacts*", "specfinder*", "socialpostcreator*", "aiticketsupport*", "common*"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]